describe('Los estudiantes login', function () {
    it('Visits los estudiantes and fails at login', function () {
        cy.visit('https://losestudiantes.co')
        cy.contains('Cerrar').click()
        cy.contains('Ingresar').click()
        cy.get('.cajaLogIn').find('input[name="correo"]').click().type("wrongemail@example.com")
        cy.get('.cajaLogIn').find('input[name="password"]').click().type("1234")
        cy.get('.cajaLogIn').contains('Ingresar').click()
        cy.contains('El correo y la contraseña que ingresaste no figuran en la base de datos. Intenta de nuevo por favor.')
    })
    it('SignUp', function () {
        cy.visit('https://losestudiantes.co')
        cy.contains('Cerrar').click()
        cy.contains('Ingresar').click()
        cy.get('.cajaSignUp').find('input[name="nombre"]').click().type("juan")
        cy.get('.cajaSignUp').find('input[name="apellido"]').click().type("cifuentes")
        cy.get('.cajaSignUp').find('input[name="correo"]').click().type("juanca0517@gmail.com")
        cy.get('.cajaSignUp').find('select[name="idUniversidad"]').select('Universidad de los Andes')
        cy.get('.cajaSignUp').find('select[name="idPrograma"]').select('Arte')
        cy.get('.cajaSignUp').find('input[name="password"]').click().type("78945612")
        cy.get('.cajaSignUp').find('input[name="acepta"]').click()
        cy.get('.cajaSignUp').contains('Registrarse').click()

    })
    it('Login existoso', function () {
        cy.visit('https://losestudiantes.co')
        cy.contains('Cerrar').click()
        cy.contains('Ingresar').click()
        cy.get('.cajaLogIn').find('input[name="correo"]').click().type("juanca0517@gmail.com")
        cy.get('.cajaLogIn').find('input[name="password"]').click().type("78945612")
        cy.get('.cajaLogIn').contains('Ingresar').click()
    })
    it('Login cuenta existente', function () {
        cy.visit('https://losestudiantes.co')
        cy.contains('Cerrar').click()
        cy.contains('Ingresar').click()
        cy.get('.cajaSignUp').find('input[name="nombre"]').click().type("juan")
        cy.get('.cajaSignUp').find('input[name="apellido"]').click().type("cifuentes")
        cy.get('.cajaSignUp').find('input[name="correo"]').click().type("juanca0517@gmail.com")
        cy.get('.cajaSignUp').find('select[name="idUniversidad"]').select('Universidad de los Andes')
        cy.get('.cajaSignUp').find('select[name="idPrograma"]').select('Arte')
        cy.get('.cajaSignUp').find('input[name="password"]').click().type("78945612")
        cy.get('.cajaSignUp').find('input[name="acepta"]').click()
        cy.get('.cajaSignUp').contains('Registrarse').click()
        cy.contains('Ya existe un usuario registrado con el correo')
        cy.contains('Ok').click()
    })
    it('Busqueda de profesor', function () {
        cy.visit('https://losestudiantes.co')
        cy.contains('Cerrar').click()
        cy.contains('Busca un profesor o materia').click()
        cy.get('div[class="Select-input"]').find('input[role="combobox"]').type("Maria Carolina Olarte Olarte")
    })
    it('Acceder a la pagina de un profesor', function () {
        cy.visit('https://losestudiantes.co')
        cy.contains('Cerrar').click()
        cy.contains('Alfabético').click()
        cy.get('.profesores').get('.profesor').find('a[href="universidad-de-los-andes/matematicas/profesores/adolfo-jose-quiroz-salazar"]').click()
    })
    it('Filtrar asignatura docente', function () {
        cy.visit('https://losestudiantes.co')
        cy.contains('Cerrar').click()
        cy.contains('Alfabético').click()
        cy.get('.profesores').get('.profesor').find('a[href="universidad-de-los-andes/matematicas/profesores/adolfo-jose-quiroz-salazar"]').click()
        cy.get('.labelHover').find('input[name="id:MATE1209"]').click()
        cy.get('.labelHover').find('input[name="id:MATE1214C"]').click()
        cy.get('.labelHover').find('input[name="id:MATE1214C"]').click()
    })
})